output "service_name" {
  value       = helm_release.grafana.name
  description = "Helm release name"
}

output "namespace" {
  value       = var.namespace
  description = "Namespace Grafana was installed into"
}

output "admin_password_cmd" {
  description = "Command to fetch the autogenerated admin password (if not set explicitly)"
  value       = "kubectl get secret ${helm_release.grafana.name} -n ${var.namespace} -o jsonpath='{.data.admin-password}' | base64 -d; echo"
}

output "svc_hint" {
  value       = "kubectl get svc -n ${var.namespace} -l app.kubernetes.io/name=grafana"
  description = "Command hint to find Grafana's EXTERNAL-IP"
}
