# aws/modules/grafana/outputs.tf
locals {
  # null-safe normalization of host
  host_str_out  = var.host == null ? "" : trimspace(var.host)
  have_host_out = length(local.host_str_out) > 0

  # safe helm release name even when count = 0
  rel_name_out = can(one(helm_release.grafana[*].name)) ? one(helm_release.grafana[*].name) : null
}

output "hostname" {
  description = "Grafana hostname passed to the module (may be empty)."
  value       = local.have_host_out ? local.host_str_out : null
}

output "url" {
  description = "HTTPS URL to Grafana when a host is set."
  value       = local.have_host_out ? "https://${local.host_str_out}" : null
}

output "login_url" {
  description = "Login URL to Grafana when a host is set."
  value       = local.have_host_out ? "https://${local.host_str_out}/login" : null
}

output "service_name" {
  description = "Helm release name."
  value       = local.rel_name_out
}

output "namespace" {
  description = "Namespace Grafana was installed into."
  value       = local.rel_name_out != null ? var.namespace : null
}

output "admin_password_cmd" {
  description = "Command to fetch the autogenerated admin password (if not set explicitly)."
  value       = local.rel_name_out != null ? "kubectl get secret ${local.rel_name_out} -n ${var.namespace} -o jsonpath='{.data.admin-password}' | base64 -d; echo" : null
}

output "svc_hint" {
  description = "Command hint to find Grafana's Service."
  value       = local.rel_name_out != null ? "kubectl get svc -n ${var.namespace} -l app.kubernetes.io/name=grafana" : null
}