# aws/modules/grafana/outputs.tf
# Put this at the top of outputs.tf (or in a locals {} there)
locals {
  grafana_name = can(one(helm_release.grafana[*].name)) ? one(helm_release.grafana[*].name) : null
}

output "service_name" {
  description = "Helm release name"
  value       = local.grafana_name
}

output "namespace" {
  description = "Namespace Grafana was installed into"
  value       = local.grafana_name != null ? var.namespace : null
}

output "admin_password_cmd" {
  description = "Command to fetch the autogenerated admin password (if not set explicitly)"
  value = (
    local.grafana_name != null
    ? "kubectl get secret ${local.grafana_name} -n ${var.namespace} -o jsonpath='{.data.admin-password}' | base64 -d; echo"
    : null
  )
}

output "svc_hint" {
  description = "Command hint to find Grafana's EXTERNAL-IP"
  value = (
    local.grafana_name != null
    ? "kubectl get svc -n ${var.namespace} -l app.kubernetes.io/name=grafana"
    : null
  )
}


